ALTER TABLE "crm_company" ADD COLUMN "hs_object_id" varchar;
ALTER TABLE "crm_company" ADD COLUMN "hs_name" varchar;
ALTER TABLE "crm_company" ADD COLUMN "hs_domain" varchar;
ALTER TABLE "crm_company" ADD COLUMN "hs_created_date" timestamp;
ALTER TABLE "crm_company" ADD COLUMN "hs_updated_date" timestamp;
ALTER TABLE "crm_company" ADD COLUMN "archived" boolean;
ALTER TABLE "crm_deals" ADD COLUMN "hs_name" varchar NOT NULL;
ALTER TABLE "crm_deals" ADD COLUMN "hs_stage" varchar NOT NULL;
ALTER TABLE "crm_deals" ADD COLUMN "hs_amount" varchar NOT NULL;
ALTER TABLE "crm_deals" ADD COLUMN "hs_close_date" timestamp;
ALTER TABLE "crm_deals" ADD COLUMN "hs_created_at" timestamp NOT NULL;
ALTER TABLE "crm_deals" ADD COLUMN "hs_updated_at" timestamp NOT NULL;
ALTER TABLE "crm_deals" ADD COLUMN "hs_object_id" varchar NOT NULL;
ALTER TABLE "crm_deals" ADD COLUMN "hs_pipeline" varchar NOT NULL;
ALTER TABLE "crm_company" DROP COLUMN IF EXISTS "name";
ALTER TABLE "crm_company" DROP COLUMN IF EXISTS "domain";
ALTER TABLE "crm_deals" DROP COLUMN IF EXISTS "name";
ALTER TABLE "crm_deals" DROP COLUMN IF EXISTS "stage";
ALTER TABLE "crm_deals" DROP COLUMN IF EXISTS "amount";
ALTER TABLE "crm_deals" DROP COLUMN IF EXISTS "close_date";
ALTER TABLE "crm_deals" DROP COLUMN IF EXISTS "create_date";
ALTER TABLE "crm_deals" DROP COLUMN IF EXISTS "last_modified_date";
ALTER TABLE "crm_deals" DROP COLUMN IF EXISTS "object_id";
ALTER TABLE "crm_deals" DROP COLUMN IF EXISTS "pipeline";
DROP INDEX IF EXISTS "name_domain_user_id_index";
DROP INDEX IF EXISTS "name_user_id_index";
CREATE UNIQUE INDEX IF NOT EXISTS "hs_id_user_id_index" ON "crm_company" ("hs_object_id","user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "hs_id_user_id_index" ON "crm_deals" ("hs_object_id","user_id");